version: "3.8"

services:
  rosenFrontend:
    container_name: docker-rosen-front-c
    image: docker-rosen-front-i
    build:
      context: .
      dockerfile: rosenFrontend/Dockerfile
    ports:
      - 3000:3000
  BE:
    container_name: docker-rosen-back-c
    image: docker-rosen-back-i
    build:
      context: .
      dockerfile: BE/Dockerfile
    ports:
      - "8000:8000"
